from pathlib import Path

path = Path('AUSNAHMEZUSTAND_FINAL.md')
text = path.read_text(encoding='utf-8')

repls = [
("Nicht den Namen. Die Adresse.", "Sein Blick blieb an der Adresse hängen, nicht am Namen."),
("Nicht weil er falsch war.\n\nWeil er sich anhörte wie etwas, das Daniel selbst gesagt hätte.", "Falsch war er nicht. Was Daniel störte: Er hörte sich an wie etwas, das Daniel selbst gesagt hätte."),
("Das war im Moment wichtig.\n\nNicht für Heller.\n\nFür Daniel.", "Für Daniel war das im Moment wichtiger als für Heller."),
("Nicht gut genug, um den ganzen Zusammenhang zu erklären.\n\nGut genug, um den Betriebshof nicht mehr als bloßen Verkehrsunfall zu behandeln.", "Für den ganzen Zusammenhang reichte es nicht. Für mehr als einen bloßen Verkehrsunfall schon."),
("Nicht fünf Stunden mit Beweisen.\n\nFünf Stunden mit Hinweisen.", "Es waren fünf Stunden mit Hinweisen, nicht mit Beweisen."),
("Nicht dieselbe Ansicht wie am Abend.\n\nLinks standen die Informationen, die sie zu einem Zeitpunkt tatsächlich gehabt hatten.", "Diesmal nahm er eine andere Ansicht als am Abend. Links standen die Informationen, die sie zu einem Zeitpunkt tatsächlich gehabt hatten."),
("Nicht Daniel allein.\n\nDas war ihm wichtig.", "Keiner davon lag bei Daniel allein. Das war ihm wichtig."),
("Nicht in Prozent. Nicht als Formel. Aber einen Maßstab.", "Keinen Wert in Prozent, keine Formel, aber immerhin einen Maßstab."),
("Nicht zu einem Live-Standort. Nicht zu einem geheimen Bewegungsbild.\n\nNur zu einer Frage, die sich in vorhandenen geschützten Daten aus einem anderen Verfahren beantworten ließ: War dieses Kennzeichen dort schon einmal zusammen mit einem relevanten Fahrzeug oder an einem relevanten Ort erfasst worden?", "Der schnellere Weg lieferte weder Live-Standort noch geheimes Bewegungsbild. Er führte nur zu einer Frage, die sich in vorhandenen geschützten Daten aus einem anderen Verfahren beantworten ließ: War dieses Kennzeichen dort schon einmal zusammen mit einem relevanten Fahrzeug oder an einem relevanten Ort erfasst worden?"),
("Nicht für den Altbestand.\n\nFür Warten.", "Die freie Zeile war fürs Warten bestimmt, nicht für den Altbestand."),
("Daniel öffnete das interne System.\n\nNicht die normale Fallansicht.\n\nDen geschützten Altbestand, den er kannte, weil er vor Monaten selbst an einem anderen Vorgang gearbeitet hatte.", "Daniel öffnete das interne System, ging an der normalen Fallansicht vorbei und in den geschützten Altbestand, den er kannte, weil er vor Monaten selbst an einem anderen Vorgang gearbeitet hatte."),
("Nicht als Bild.\n\nAls Tatsache.", "Diesmal dachte er an ihn als Tatsache, nicht als Bild."),
("Nicht weil er irgendwohin musste.\n\nEr ging zur Tür, öffnete sie und sah in den Flur.", "Er musste nirgendwohin. Trotzdem ging er zur Tür, öffnete sie und sah in den Flur."),
("Die Quelle konnte genau diesen Moment gebaut haben.\n\nNicht die Gefahr. Den Moment.", "Vielleicht hatte die Quelle nicht die Gefahr gebaut, sondern genau diesen Moment."),
("Nicht alles, was technisch möglich war.\n\nNur das, was seine eine Frage beantworten konnte.", "Er nutzte nur den Ausschnitt, den seine eine Frage brauchte, statt alles technisch Mögliche aufzuziehen."),
("Nicht sauberer.", "Sauber wurde er dadurch nicht."),
("Nicht nur wegen der Lage.\n\nAuch weil der Treffer dann nachträglich weniger allein dastand.", "Dabei ging es ihm nicht nur um die Lage. Der Treffer würde dann nachträglich weniger allein dastehen."),
("Nicht der weiße Lieferwagen aus dem alten Verfahren.\n\nEin dunkler Kleinbus.", "Es war ein dunkler Kleinbus, nicht der weiße Lieferwagen aus dem alten Verfahren."),
("Nicht weil die Gefahr kleiner geworden war.", "Die Gefahr war dadurch kein Stück kleiner geworden."),
("Nicht seinen Altbestand.\n\nNicht die Behauptung, das Warnfenster müsse stimmen.\n\n„Bewertung?“ kam die Rückfrage.", "Sein Altbestand und die Behauptung, das Warnfenster müsse stimmen, blieben außen vor.\n\n„Bewertung?“ kam die Rückfrage."),
("Nicht am angekündigten Parkhaus.\n\nHundertsechzig Meter weiter an einer Seiteneinfahrt.", "Er hielt hundertsechzig Meter weiter an einer Seiteneinfahrt statt am angekündigten Parkhaus."),
("Nicht nur die markierten Stellen.", "Er beschränkte sich dabei nicht auf die markierten Stellen."),
("Nicht weil er Berg misstraute.\n\nWeil er später nicht erzählen wollte, die Nicht-Sanktion sei irgendwie einfach passiert.", "Misstrauen gegen Berg war nicht der Grund. Daniel wollte später nicht erzählen, die Nicht-Sanktion sei irgendwie einfach passiert."),
("Nicht wegen des Kennzeichens.\n\nWegen der Begrenzung.", "Entscheidend war die Begrenzung, nicht das Kennzeichen."),
("Nicht nur das Ergebnis. Die Art, wie er sich selbst beschränkt hatte.", "Ihn interessierte inzwischen ebenso, wie er sich selbst beschränkt hatte, wie das Ergebnis."),
("Nicht Hellers Name.", "Hellers Name tauchte dort nicht auf."),
("Nicht eindeutig.", "Eindeutig war er trotzdem nicht."),
("Nicht alle.", "Andere Wege blieben offen."),
("Nicht als Entlastung. Als Maßstab dafür, worüber Mika log.", "Er brauchte sie jetzt als Maßstab dafür, worüber Mika log, nicht als Entlastung."),
("Nicht weil Mika dort ehrlich sein musste.\n\nWeil Daniel keinen Grund mehr hatte, jedes Nichtwissen als besonders gute Lüge zu behandeln.", "Mikas Ehrlichkeit war dafür nicht entscheidend. Daniel hatte nur keinen Grund mehr, jedes Nichtwissen als besonders gute Lüge zu behandeln."),
("Die drei Treffer waren das Problem.\n\nNicht das Kennzeichen.\n\nNicht der Altbestand.\n\nDie Zahl.", "Das Problem lag weder im Kennzeichen noch im Altbestand, sondern in der Zahl der Treffer."),
("Nicht die Erklärung. Aber die Form eines Geheimnisses.", "Eine Erklärung war es noch nicht, aber immerhin die Form eines Geheimnisses."),
("Nicht zwingend direkt aus dem System.", "Sie musste allerdings nicht direkt aus dem System stammen."),
("Nicht jeder sah alles.", "Die Sicht war nach Rollen getrennt."),
("Nicht heimlich.\n\nIm Gegenteil.", "Und dieses Interesse war offen."),
("Nicht als Wunderwerkzeug.\n\nAls besser organisierter Raum für bereits zulässige Fragen.", "Sie funktionierte als besser organisierter Raum für bereits zulässige Fragen, nicht als Wunderwerkzeug."),
("Nicht wegen Ideologie.\n\nWeil elf Minuten sich im Alltag sofort vernünftig anfühlten.", "Der Grund war banal: Elf Minuten fühlten sich im Alltag sofort vernünftig an."),
("Nicht rot. Nicht markiert. Nur oben, weil er die meisten Überschneidungen hatte.", "Er war weder rot noch markiert; er stand nur oben, weil er die meisten Überschneidungen hatte."),
("Nicht Weber.\n\nNicht einmal derselbe Subunternehmer.\n\nDie erste Rückmeldung war banal.", "Der Treffer führte weder zu Weber noch zum selben Subunternehmer.\n\nDie erste Rückmeldung war banal."),
("Nicht das private Auto des Fahrers.\n\nEin Transporter des Dienstleisters.", "Es war ein Transporter des Dienstleisters, nicht das private Auto des Fahrers."),
("Nicht direkt.", "Jedenfalls nicht direkt."),
("Jonas nannte einen Namen.\n\nNicht Weber.", "Jonas nannte einen Namen. Es war nicht Weber."),
("Die Kamera zeigte die Seitentür schräg. Ein Mann mit Mütze hielt den Ausweis an den Leser. Gesicht nur teilweise sichtbar.\n\nNicht Weber.", "Die Kamera zeigte die Seitentür schräg. Ein Mann mit Mütze hielt den Ausweis an den Leser. Gesicht nur teilweise sichtbar. Der Mann war nicht Weber."),
("Ein Mann mit Mütze.\n\nNicht Weber.", "Ein Mann mit Mütze. Wieder war es nicht Weber."),
("Nicht vollständig.", "Vollständig war er trotzdem nicht."),
("Nicht weil zweiundzwanzig Minuten den Schaden erklärten.\n\nSondern weil sie zeigten, wie schnell eine vorläufige Bewertung ein Eigenleben bekommen konnte, sobald eine andere Organisation darauf reagierte.", "Die zweiundzwanzig Minuten erklärten den Schaden nicht. Sie zeigten aber, wie schnell eine vorläufige Bewertung ein Eigenleben bekommen konnte, sobald eine andere Organisation darauf reagierte."),
("Nicht systematisch.", "Systematisch ging er dabei nicht vor."),
("Berg hatte ihm den Vorgang erst danach auf den Tisch gelegt.\n\nNicht Stunden vorher.\n\nDanach.", "Berg hatte ihm den Vorgang erst danach auf den Tisch gelegt, keineswegs Stunden vorher."),
("Nicht genug, um ihn als zuständigen Bearbeiter des neuen Falls vorherzusehen.", "Für eine Vorhersage seiner Zuständigkeit reichte das nicht."),
("Nicht als Heldengeschichte.\n\nAls Beispiel.", "Die Übersicht erzählte keine Heldengeschichte; sie benutzte den Fall als Beispiel."),
("Er hatte das gewusst.\n\nNicht in dieser Form.", "Dass der Fall intern Referenz war, hatte Daniel gewusst. Diese Form kannte er nicht."),
("Nicht nur seine Information konnte Teil eines Mechanismus sein.\n\nSeine Vernunft konnte es auch.", "Zum Mechanismus konnte neben seiner Information auch seine Vernunft gehören."),
("Nicht in den Quellenstand. Nicht neben die Lieferkennung.\n\nAuf ein separates Blatt.", "Er schrieb ihn auf ein separates Blatt, außerhalb des Quellenstands und weg von der Lieferkennung."),
("Nicht einmal eine besonders seltene.", "Selten war sie nicht einmal."),
("Nicht weil sie schlecht waren.\n\nWeil er weiter nach einer Stelle suchte, an der er wieder übernehmen konnte.", "Ihre Antworten waren nicht schlecht. Daniel suchte trotzdem weiter nach einer Stelle, an der er wieder übernehmen konnte."),
("Nicht seiner.\n\nIhrer.", "Es war ihr Kompromiss, nicht seiner."),
("Nicht das System entschied.\n\nMenschen lasen, telefonierten, verglichen, strichen wieder weg.", "Entschieden wurde weiterhin von Menschen: Sie lasen, telefonierten, verglichen, strichen wieder weg."),
("Nicht wegen ihrer normalen Fallarbeit.\n\nWegen wiederholter Kontakte zu einem internen Datenschutz- und Kontrollbereich, die in den Projektunterlagen nicht erklärt waren.", "Ihr Name stand dort wegen wiederholter Kontakte zu einem internen Datenschutz- und Kontrollbereich, die in den Projektunterlagen nicht erklärt waren, und nicht wegen ihrer normalen Fallarbeit."),
("Lena sah zu Daniel.\n\nNicht zu Berg.", "Lenas Blick ging zu Daniel, nicht zu Berg."),
("Lena wollte nicht erklären, warum sie die Kontakte hatte.\n\nNicht im Flur.\n\nNicht Daniel allein.", "Lena wollte die Kontakte weder im Flur noch Daniel allein erklären."),
("Daniel spürte Ärger.\n\nNicht weil sie unrecht hatte.\n\nWeil sie seine Zeit benutzte.", "Daniel spürte Ärger. Der galt nicht ihrer Position, sondern der Tatsache, dass sie seine Zeit benutzte."),
("Nicht um Lena mit Weber gleichzusetzen.\n\nGenau das durfte er nicht.", "Er wollte Lena damit keinesfalls Weber gleichsetzen. Genau das durfte er nicht."),
("Nicht aus Schuldgefühl, sagte er sich.\n\nZur Nachbereitung.", "Er nannte es Nachbereitung und nicht Schuldgefühl."),
("Nicht auffällig. Nur zwei Gespräche brachen eine Sekunde zu früh ab.", "Es war kaum auffällig; nur zwei Gespräche brachen eine Sekunde zu früh ab."),
("Nicht weil Lena damit unrecht hatte.\n\nSondern weil ihre Unschuld nichts darüber sagte, ob die anderen Treffer falsch waren.", "Lenas Einwand war nicht falsch. Ihre Unschuld sagte nur nichts darüber, ob die anderen Treffer falsch waren."),
("Nicht still.\n\nAndere Treffer liefen parallel. Zwei wurden geschlossen. Einer ging wegen fehlender Rückmeldung in die nächste Schicht. Die Lieferadresse blieb auf Daniels Bildschirm, obwohl nichts Neues passierte.", "Still war dieses Warten nicht. Andere Treffer liefen parallel. Zwei wurden geschlossen. Einer ging wegen fehlender Rückmeldung in die nächste Schicht. Die Lieferadresse blieb auf Daniels Bildschirm, obwohl nichts Neues passierte."),
("Nicht vom Fahrer.\n\nVom Fahrzeugstandort.", "Das Foto zeigte nicht den Fahrer, sondern den Fahrzeugstandort."),
("Nicht Quelle plus Quelle.\n\nNicht Korrelation plus Interpretation.\n\nZwei Wege.", "Entscheidend waren zwei getrennte Wege statt Quelle plus Quelle oder Korrelation plus Interpretation."),
("Nicht weil plötzlich alles erlaubt war.\n\nWeil die Kontakte bereits standen, die Zuständigkeiten klar waren und dieselben rechtmäßig vorhandenen Informationen im Projekt nicht mehr nacheinander durch mehrere Stellen wandern mussten.", "Schnell war die Prüfung nicht wegen zusätzlicher Befugnisse, sondern weil die Kontakte bereits standen, die Zuständigkeiten klar waren und dieselben rechtmäßig vorhandenen Informationen im Projekt nicht mehr nacheinander durch mehrere Stellen wandern mussten."),
("Nicht ihr Job, ihm die Entscheidung abzunehmen.", "Sie würde ihm die Entscheidung nicht abnehmen; das war nicht ihr Job."),
("Nicht weil er ihn nicht verstanden hatte.\n\nWeil er wusste, was jetzt folgte.", "Verstanden hatte er ihn. Er las ihn noch einmal, weil er wusste, was jetzt folgte."),
("Nicht leichter.", "Schwerer, nicht leichter."),
("Nicht als Erfolgsquote.\n\nNur als Nenner.", "Die Zahl diente nur als Nenner, nicht als Erfolgsquote."),
("Nicht böse.\n\nNur müde.", "Das Lachen klang müde, ohne jede Bosheit."),
("Nicht seine.", "Die Entscheidung gehörte jemand anderem."),
("Nicht weil Berg ihm die Entscheidung zuschieben wollte.\n\nWeil Daniel die Grenze selbst formuliert hatte.", "Berg schob ihm die Entscheidung nicht zu. Daniel hatte die Grenze selbst formuliert."),
("Nicht für eine Maßnahme gegen jemanden. Nicht für die Ausweitung einer Prüfung.", "Die Verschiebung betraf weder eine Maßnahme gegen jemanden noch die Ausweitung einer Prüfung."),
("Nicht die Zusammenfassung. Den Rohstand.", "Jonas öffnete den Rohstand statt der Zusammenfassung."),
("Nicht weil es Heller entlastete.\n\nWeil es Daniel zwang, jede Lücke einzeln zu verdienen.", "Heller entlastete das nicht. Es zwang Daniel vielmehr, jede Lücke einzeln zu verdienen."),
("Nicht in diesen Worten.\n\nDie Logik dahinter.", "Die Worte waren neu, die Logik dahinter kannte er."),
("Nicht weil er mehr darin sah als vorher.\n\nSondern weil zum ersten Mal ein Fall übrig blieb, bei dem das Prüfkriterium nicht sofort zerfiel.", "Er sah darin nicht mehr als vorher. Entscheidend war, dass zum ersten Mal ein Fall übrig blieb, bei dem das Prüfkriterium nicht sofort zerfiel."),
("Nicht für die Frage, die ihn interessierte.", "Für die Frage, die ihn interessierte, reichte es trotzdem nicht."),
("Nicht die Zusammenfassung, die sie seit Tagen zitierten.\n\nDen ursprünglichen Vorgang.", "Er öffnete den ursprünglichen Vorgang statt der Zusammenfassung, die sie seit Tagen zitierten."),
("Der bereits bekannte Randkontakt.\n\nNicht der spätere Betriebshof.\n\nNicht die Verletzung.\n\nNicht die spätere Täterstruktur in ihrer heutigen Klarheit.", "Der bereits bekannte Randkontakt war alles, was damals konkret vorlag. Betriebshof, Verletzung und heutige Klarheit der Täterstruktur kamen erst später."),
("Nicht auf die Diagnose.\n\nAuf die Reihenfolge.", "Ihn interessierte diesmal die Reihenfolge, nicht die Diagnose."),
("Heller darunter.\n\nNicht allein.", "Heller stand darunter, aber nicht allein."),
("Nicht aus dem Verdacht.\n\nAus der einfachen Geschichte.", "Der Verdacht blieb; nur aus der einfachen Geschichte fiel Berg heraus."),
("Nicht Hellers persönlicher Name.", "Hellers persönlicher Name stand dort nicht."),
("Nicht allein.\n\nNicht hervorgehoben.\n\nAber früh.", "Daniel war weder allein noch hervorgehoben aufgeführt, aber früh."),
("Nicht um hinauszugehen.\n\nNur weil er nicht mehr sitzen wollte.", "Er wollte nicht hinaus. Er wollte nur nicht mehr sitzen."),
("Nicht für ihre Kombination.", "Ihre Kombination war damit noch nicht abgesichert."),
("Daniel sah wieder die alte Bewertung.\n\nNicht vorschnell eskalierend.\n\nHohe Akzeptanz operativ und juristisch.", "Daniel sah wieder die alte Bewertung: keine vorschnelle Eskalation, hohe Akzeptanz operativ und juristisch."),
("Nicht weil er Regeln plötzlich verachtete.\n\nWeil reale Schäden die Gewichtung verändert hatten.", "Regelverachtung war nicht der Grund. Reale Schäden hatten seine Gewichtung verändert."),
("Nicht Lena.\n\nNicht Weber.\n\nNicht den Nicht-Rückbau.", "Das galt für Lena, Weber und den Nicht-Rückbau gleichermaßen."),
("Nicht weil sie Heller als Quelle bewiesen.\n\nWeil der Fall sonst wieder zu klein geworden wäre.", "Die Unterlagen bewiesen Heller nicht als Quelle. Daniel nahm sie mit, damit der Fall nicht wieder zu klein wurde."),
("Nicht weil er sie vergessen wollte.\n\nWeil er sehen wollte, ob die nächsten Entscheidungen auch ohne sie dieselben blieben.", "Vergessen wollte er die Zeile nicht. Er wollte sehen, ob die nächsten Entscheidungen auch ohne sie dieselben blieben."),
("Nicht lange.", "Der Blick dauerte nur einen Moment."),
("Nicht die ganze Beweiskette.\n\nGenug.", "Die Kurzfassung enthielt nicht die ganze Beweiskette, aber genug."),
("Nicht genug, um sich mit Nervosität zu entschuldigen.", "Für eine Entschuldigung mit Nervosität reichte die Zeit trotzdem nicht."),
("Nicht passiv.\n\nPrüfend.", "Dabei blieb er aktiv und prüfte weiter."),
("Daniel sah zuerst auf die Herkunft.\n\nNicht auf den Inhalt.\n\nDann las er.", "Daniel prüfte zuerst die Herkunft; den Inhalt las er erst danach."),
("Nicht für das Endbild, das Heller ihnen geliefert hatte.", "Für Hellers fertiges Endbild reichte es noch nicht."),
("Nicht weil sie unwichtig geworden war.\n\nWeil sie für die nächste Entscheidung nicht mehr reichen musste.", "Unwichtig war die Nachricht nicht. Für die nächste Entscheidung musste sie nur nicht mehr reichen."),
("Nicht als Erinnerung an Heller.\n\nAls Arbeitsgrundlage.", "Das Fenster blieb als Arbeitsgrundlage offen, nicht als Erinnerung an Heller."),
("Nicht als exakten Plan.\n\nAls Grenze.", "Die Zeiten dienten ihm als Grenze, nicht als exakter Plan."),
("Nicht erst zu ihrer späteren Bewertung.", "Dieser Preis gehörte schon jetzt dazu, nicht erst in die spätere Bewertung."),
("Nicht lange.\n\nDas Bild kam und ging.", "Das Bild kam kurz und ging wieder."),
("Nicht die optimistischen Werte.\n\nDie realistischen.", "Er nahm die realistischen statt der optimistischen Werte."),
("Nicht irgendwo auf dem Gelände.\n\nIn dem Bereich, dessen fachliche Zuordnung aus Daniels Strang gerade in den nächsten Schritt einfloss.", "Die Änderung lag genau in dem Bereich, dessen fachliche Zuordnung aus Daniels Strang gerade in den nächsten Schritt einfloss."),
("Nicht weil zwanzig Sekunden sicher reichten.\n\nWeil zehn zu wenig waren und dreißig vielleicht schon zu viel.", "Zwanzig Sekunden waren nicht sicher genug. Zehn waren zu wenig und dreißig vielleicht schon zu viel."),
("Auf dem Display stand die vorbereitete Meldung noch offen.\n\nNicht gesendet.", "Auf dem Display stand die vorbereitete Meldung noch offen. Sie war ungesendet geblieben."),
("Nicht weil er sie akustisch nicht verstanden hatte.\n\nWeil er einen klaren Punkt brauchte, an dem die Verantwortung für den laufenden Zugriff wieder dort lag, wo sie hingehörte.", "Akustisch hatte er die Antwort verstanden. Er brauchte die Wiederholung als klaren Punkt, an dem die Verantwortung für den laufenden Zugriff wieder dort lag, wo sie hingehörte."),
("Nicht wegen Unklarheit.\n\nWeil jedes Wort jetzt zwei Funktionen hatte: Die laufende Lage musste damit arbeiten können, und später musste nachvollziehbar bleiben, was Daniel in diesem Moment tatsächlich wusste.", "Unklar war er nicht. Er sprach langsamer, weil jedes Wort jetzt zwei Funktionen hatte: Die laufende Lage musste damit arbeiten können, und später musste nachvollziehbar bleiben, was Daniel in diesem Moment tatsächlich wusste."),
("Nicht weil die Lage kleiner wurde.\n\nWeil eine Gegenhypothese überlebt hatte.", "Die Lage war kein Stück kleiner geworden. Erleichterung brachte ihm, dass eine Gegenhypothese überlebt hatte."),
("Nicht lange.\n\nLange genug, dass Daniel jede Sekunde hörte.", "Es dauerte nur Sekunden, aber Daniel hörte jede davon."),
("Nicht alles passte zu Hellers Bild.", "Hellers Bild bekam bereits den ersten Riss."),
("Nicht ganz.\n\nNur aus einem Ohr.", "Er zog ihn nur aus einem Ohr."),
("Nicht weil der Satz falsch war.\n\nWeil er zu groß war.", "Falsch war der Satz nicht. Daniel widersprach, weil er zu groß war."),
("Nicht jeder Teil davon gehörte zu derselben moralischen Rechnung.", "Die Teile gehörten nicht alle in dieselbe moralische Rechnung."),
("Nicht warum.\n\nNur dass sie Termine verschoben hatte und einer schon zweimal angerufen hatte.", "Über die Gründe sprach Jana nicht; nur darüber, dass sie Termine verschoben hatte und einer schon zweimal angerufen hatte."),
("Nicht weil es bedrohlich klang.\n\nIm Gegenteil.", "Bedrohlich klang das Wort keineswegs. Im Gegenteil."),
("Nicht mit Grundsatzsätzen.\n\nMit Änderungen.", "Die Synopse begann mit konkreten Änderungen statt mit Grundsatzsätzen."),
("Nicht sein Name.\n\nNicht Hellers.\n\nEin abstrahierter Fall mit verzögerter Verknüpfung vorhandener Informationen, anschließendem Zeitgewinn durch gemeinsame Auswertung und verhindertem großen Schaden.", "Weder sein Name noch Hellers stand dort. Stattdessen ein abstrahierter Fall mit verzögerter Verknüpfung vorhandener Informationen, anschließendem Zeitgewinn durch gemeinsame Auswertung und verhindertem großen Schaden."),
("Nicht mit der Reichweite.\n\nMit der Frage, ob eine solche Verknüpfung überhaupt in den Raum gehörte.", "Vor drei Monaten hätte das Gespräch mit der Grundfrage begonnen, ob eine solche Verknüpfung überhaupt in den Raum gehörte, und nicht mit ihrer Reichweite."),
("Nicht spektakulär hoch.\n\nAber hoch genug, dass Daniel sofort verstand, wie anders die spätere Statistik aussehen würde, wenn nur erfolgreiche Verknüpfungen in Präsentationen auftauchten.", "Die Zahl war unspektakulär, aber hoch genug, dass Daniel sofort verstand, wie anders die spätere Statistik aussehen würde, wenn nur erfolgreiche Verknüpfungen in Präsentationen auftauchten."),
("Nicht für die Verbundprüfung.\n\nFür die Tatsache, dass auch ihr **Nicht-Einsatz** messbar bleiben sollte.", "Sein Haken galt nicht der Verbundprüfung, sondern der Forderung, auch ihren **Nicht-Einsatz** messbar zu halten."),
("Mara stellte vor.\n\nNicht lange.", "Mara stellte sie einander kurz vor."),
("Nicht ob er es richtig machte.\n\nOb es überhaupt sein Problem war.", "Er fragte inzwischen zuerst, ob es überhaupt sein Problem war, statt ob er es richtig machte."),
("Nicht dramatisch offen.\n\nEs gab nur noch keine saubere Erklärung.", "Dramatisch war daran nichts; es fehlte lediglich noch eine saubere Erklärung."),
("Nicht als roter Alarm.\n\nAls Liste.", "Die Ergebnisse kamen als Liste, nicht als roter Alarm."),
("Nicht erfunden.\n\nNur ohne den Kontext, der sie banal machte.", "Die Treffer wären real gewesen, nur ohne den Kontext, der sie banal machte."),
]

for i, (old, new) in enumerate(repls, 1):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'replacement {i} expected once, found {count}: {old[:90]!r}')
    text = text.replace(old, new, 1)

path.write_text(text, encoding='utf-8')
print(f'Applied {len(repls)} targeted replacements')
